#lang planet neil/sicp
(define (ave x1 x2) (/ (+ x1 x2) 2))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ".")
  (display (y-point p))
  (display ")"))
(define (make-segment p1 p2) (cons p1 p2))
(define (start-segment segment) (car segment))
(define (end-segment segment) (cdr segment))
(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))
(define point1 (make-point 1 2))
(define point2 (make-point 3 4))
(define segment1 (make-segment point1 point2))
(define ssg1 (start-segment segment1))
(define esg1 (end-segment segment1))
(define (midpoint-segment segment)
  (let ((x (ave (x-point (start-segment segment))
                (x-point (end-segment segment))))
        (y (ave (y-point (start-segment segment))
                 (y-point (end-segment segment)))))
    (make-point x y)))
(print-point (midpoint-segment segment1))